# Generated by Django 6.1 on 2026-08-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
